### ISSUE TITLE
undefined method `order' for stock/splitter/drop_ship.rb

### ISSUE THREAD

**Issue by ostraperlera** [spree-contrib/spree_drop_ship#61]
Hi there, 

When placing an order, I get the following error loading checkout/update/address:

`undefined local variable or method 'order' for #<Spree::Stock::Splitter::DropShip:0x007f2af9bf3648`

As far as I can tell, this is related to spree/spree@974cad4c65596d4acaf405287f47e2c37a336d05 that changes the way stock objects are handled. 

Among other changes, build_package goes from taking 3 arguments (stock_location, order, contents) to just two (stock_location, contents). 

Therefore removing the reference to "order" in line 23 in stock/splitter/drop_ship.rb seems to solve the problem, but I can't tell if that's the best approach or it will break something else:

`` split_packages << Spree::Stock::Package.new(stock_location, [content])``

I've read you're not maintining this plugin anymore, but I thought I'd brought this issue up and see if it's easy enough that you'd consider looking into it.  

This is the trace:

````
/home/devs/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/spree_drop_ship-1843b5c5e167/app/models/spree/stock/splitter/drop_ship.rb:23:in `block (2 levels) in split'
/home/devs/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/spree_drop_ship-1843b5c5e167/app/models/spree/stock/splitter/drop_ship.rb:14:in `each'
/home/devs/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/spree_drop_ship-1843b5c5e167/app/models/spree/stock/splitter/drop_ship.rb:14:in `block in split'
/home/devs/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/spree_drop_ship-1843b5c5e167/app/models/spree/stock/splitter/drop_ship.rb:8:in `each'
/home/devs/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/spree_drop_ship-1843b5c5e167/app/models/spree/stock/splitter/drop_ship.rb:8:in `split'
/home/devs/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/spree-84ab989f670c/core/app/models/spree/stock/splitter/base.rb:19:in `return_next'
/home/devs/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/spree-84ab989f670c/core/app/models/spree/stock/splitter/backordered.rb:17:in `split'
/home/devs/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/spree-84ab989f670c/core/app/models/spree/stock/splitter/base.rb:19:in `return_next'
/home/devs/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/spree-84ab989f670c/core/app/models/spree/stock/splitter/shipping_category.rb:10:in `split'
/home/devs/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/spree-84ab989f670c/core/app/models/spree/stock/packer.rb:16:in `packages'
/home/devs/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/spree-84ab989f670c/core/app/models/spree/stock/coordinator.rb:37:in `block in build_packages'
````

And the relevant part of my gemfile:

````
gem 'spree', github: 'spree/spree', branch: '2-4-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '2-4-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-4-stable'
gem 'spree_bootstrap_frontend', github: '200Creative/spree_bootstrap_frontend', branch: 'master'
gem 'spree_drop_ship', github: 'jdutil/spree_drop_ship', branch: '2-4-beta'
gem 'spree_marketplace', github: 'ostraperlera/spree_marketplace'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n', branch: '2-4-stable'
gem 'datashift', github: 'autotelik/datashift', branch: 'master'
gem 'datashift_spree', github: 'autotelik/datashift_spree'
````

Thanks in advance!

**Comment by Salet** [comment]
I have the same problem here. I'm new to spree tho, so have no suggestions for a fix.
